collections:
  artists:
    output: true

defaults:
  - scope:
      path: ""
      type: "artists"
    values:
      layout: "artist"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: /HiddenSounds
page_gen:
  - data: songs
    template: song
    name: sname
  - data: artists
    template: artist
    name: sname